version: 2.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  nuget sources add -name CSharpRuleSet -source https://ci.appveyor.com/nuget/csharpruleset-rxwtqx7d05sl
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
init:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME" }
build:
  verbosity: minimal
test_script:
- ps: dotnet test CoreUtils.Tests\System1Group.Lib.CoreUtils.Tests.csproj
after_build:
- ps: dotnet pack --configuration Release CoreUtils\System1Group.Lib.CoreUtils.csproj
on_success:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Get-ChildItem -Path .\ -Include *.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name } } else { Write-Host "Skip uploading artefacts for non-tag build." }
